sudo: false
dist: trusty
language: node_js
node_js: node
addons:
  apt:
    packages:
      - google-chrome-stable
  sauce_connect: true
before_script:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start &
  - npm run http-server &
  - sleep 3
script: npm run ci
